# BoardConfig.mk for Realme C30s Ultimate ROM
# Android 15+ Custom ROM Configuration

# Platform
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_VARIANT := cortex-a76
TARGET_CPU_ABI := arm64-v8a

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_VARIANT := cortex-a55
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi

# Board Information
TARGET_BOARD_PLATFORM := ums512
TARGET_BOOTLOADER_BOARD_NAME := rmx3690
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

# Kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_SOURCE := kernel/realme/rmx3690
TARGET_KERNEL_CONFIG := rmx3690_defconfig
TARGET_KERNEL_VARIANT_CONFIG := rmx3690_variant_defconfig
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_KERNEL_CLANG_VERSION := r487747c
TARGET_KERNEL_CLANG_PATH := $(shell pwd)/prebuilts/clang/host/linux-x86/clang-r487747c

# Kernel CMDLINE
BOARD_KERNEL_CMDLINE := \
    console=ttyS1,115200n8 \
    androidboot.selinux=permissive \
    androidboot.hardware=rmx3690 \
    androidboot.boot_devices=soc@10000000 \
    msm_rtb.filter=0x237 \
    ehci-hcd.park=3 \
    lpm_levels.sleep_disabled=1 \
    service_locator.enable=1 \
    swiotlb=2048 \
    androidboot.configfs=true \
    androidboot.usbcontroller=a600000.dwc3 \
    firmware_class.path=/vendor/firmware_mnt/image \
    loop.max_part=7

# Kernel Binary
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x11088000
BOARD_SECOND_OFFSET := 0xb0000000
BOARD_KERNEL_TAGS_OFFSET := 0x07c08000
BOARD_DTB_OFFSET := 0x07c08000
BOARD_BOOTIMG_HEADER_VERSION := 2

# Boot Image
BOARD_MKBOOTIMG_ARGS := \
    --kernel_offset $(BOARD_KERNEL_OFFSET) \
    --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
    --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) \
    --dtb_offset $(BOARD_DTB_OFFSET) \
    --header_version $(BOARD_BOOTIMG_HEADER_VERSION) \
    --pagesize $(BOARD_KERNEL_PAGESIZE) \
    --board ""

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := realme_dynamic_partitions
BOARD_REALME_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_REALME_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system system_ext product vendor vendor_dlkm odm odm_dlkm

# File Systems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4

# Partition Mount Points
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 1073741824
BOARD_VENDORIMAGE_PARTITION_RESERVED_SIZE := 104857600
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE := 104857600

# AVB (Android Verified Boot)
BOARD_AVB_ENABLE := true
BOARD_AVB_ROLLBACK_INDEX := 0
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --set_hashtree_disabled_flag
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2

# AVB Keys
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_ALGORITHM := SHA256_RSA2048

# Boot AVB
BOARD_AVB_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_BOOT_ALGORITHM := SHA256_RSA2048
BOARD_AVB_BOOT_ROLLBACK_INDEX := 0
BOARD_AVB_BOOT_ROLLBACK_INDEX_LOCATION := 1

# Recovery AVB
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA2048
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 0
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 2

# Graphics
USE_OPENGL_RENDERER := true
TARGET_USES_HWC2 := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_USES_GRALLOC1 := true
TARGET_USES_VULKAN := true
TARGET_SCREEN_DENSITY := 280

# Display
TARGET_USES_DISPLAY_RENDER_INTENTS := true
TARGET_USES_COLOR_METADATA := true
TARGET_HAS_HDR_DISPLAY := true
TARGET_HAS_WIDE_COLOR_DISPLAY := true

# Audio
USE_XML_AUDIO_POLICY_CONF := 1
AUDIO_FEATURE_ENABLED_EXTENDED_COMPRESS_FORMAT := true
AUDIO_FEATURE_ENABLED_PROXY_DEVICE := true
AUDIO_FEATURE_ENABLED_SSR := true
AUDIO_FEATURE_ENABLED_AAC_ADTS_OFFLOAD := true
BOARD_USES_ALSA_AUDIO := true

# Custom Audio Features
TARGET_ENABLE_DOLBY_ATMOS := true
TARGET_ENABLE_VIPER4ANDROID := true
AUDIO_FEATURE_ENABLED_EXTN_RESAMPLER := true
AUDIO_FEATURE_ENABLED_HW_ACCELERATED_EFFECTS := true

# Camera
TARGET_USES_QTI_CAMERA_DEVICE := true
CAMERA_DAEMON_NOT_PRESENT := true
TARGET_CAMERA_NEEDS_CLIENT_INFO := true

# Media
TARGET_USES_MEDIA_EXTENSIONS := true
TARGET_ENABLE_MEDIADRM_64 := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/realme/rmx3690/bluetooth

# WiFi
BOARD_WLAN_DEVICE := bcmdhd
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_bcmdhd
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true
WPA_SUPPLICANT_VERSION := VER_0_8_X

# SELinux
BOARD_SEPOLICY_DIRS += \
    device/realme/rmx3690/sepolicy/vendor \
    device/realme/rmx3690/sepolicy/private

SELINUX_IGNORE_NEVERALLOWS := false

# Custom SELinux Policies
include device/realme/rmx3690/sepolicy/custom_sepolicy.mk

# Custom Features
include device/realme/rmx3690/configs/features/features.mk

# Performance Optimizations
TARGET_ENABLE_GAMING_MODE := true
TARGET_USE_PERFORMANCE_PROFILES := true
TARGET_USE_ADAPTIVE_PERFORMANCE := true

# Security
TARGET_ENABLE_PRIVACY_INDICATORS := true
TARGET_USE_ADVANCED_SECURITY := true
TARGET_USE_SYSTEM_SECURITY_PATCHES := true

# Thermal Management
TARGET_USE_THERMAL_CONTROL := true
TARGET_USE_INTELLI_THERMAL := true

# Battery Optimization
TARGET_ENABLE_BATTERY_OPTIMIZATIONS := true
TARGET_USE_SMART_BATTERY := true

# Network
TARGET_ENABLE_NETWORK_OPTIMIZATIONS := true
TARGET_USE_ADAPTIVE_NETWORK := true

# Build Properties
TARGET_SYSTEM_PROP += device/realme/rmx3690/system.prop
TARGET_VENDOR_PROP += device/realme/rmx3690/vendor.prop

# OTA
TARGET_OTA_ASSERT_DEVICE := rmx3690,RE546B

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_RECOVERY_FSTAB := device/realme/rmx3690/recovery.fstab
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_USES_RECOVERY_AS_BOOT := false

# Custom Recovery Options
TARGET_RECOVERY_UI_MARGIN_HEIGHT := 100
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"

# Include vendor if exists
-include vendor/realme/rmx3690/BoardConfigVendor.mk

# Custom BoardConfig Extensions
include device/realme/rmx3690/configs/boardconfig_extensions.mk

# Debug
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true

# Enable building with ccache
CCACHE_EXEC ?= $(shell which ccache)
USE_CCACHE := true

# Final flags
ALLOW_MISSING_DEPENDENCIES := false
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
